# Generated by Django 4.1.5 on 2023-01-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_votes',
            field=models.IntegerField(default=0),
        ),
    ]
